name: lecternus
description: A new Flutter application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  sqflite: ^2.0.0+3
  flutter:
    sdk: flutter

  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  
  mask_text_input_formatter: ^2.5.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logoTeste.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logoTeste.png"

flutter:
  uses-material-design: true

  assets:
      - assets/images/

